/*
 * Source.java
 */

import javax.swing.*;
import java.io.*;
import java.net.*;
import java.awt.*;
import java.util.*;

public class sourceModule extends javax.swing.JFrame implements Runnable {
	
		byte content [] = new byte [60000];
		String str;
		String s;
		int j;
		JFileChooser fc;
		String path;
		String file;
		String filename;
		String filecontent;
		String jcombovalue;
		int i;
		int count=0;
		Vector vec,vec1;
		Vector vector;
		String ip;
		String temp, temp1;
		
		public static DefaultListModel model;
		public static DefaultListModel model1;
		
		/*Create new form Source */
		public sourceModule() {
			initComponents();
			setBounds(150,150,710,570);
			vec = new Vector();
			model = new DefaultListModel();
			System.out.println("1");
			vec = loadLanUser();
			System.out.println("2");
			System.out.println("vec="+vec);
			for(j=0; j<vec.size();j++) {
				s = vec.get(j).toString();
			}
			System.out.println("The String s value is: "+s);
			for(j=0; j<vec.size();j++) {
				String ss = (String)vec.get(j);
				model.addElements(ss);
				jComboBox1.addItems(ss);
			}
			try 
			{
				BufferedReader br = new BufferedReader(new FileReader("nextip.txt"));
				while((temp = br.readLine())!=null)
				{
					vec.addElement(temp);
					jComboBox1.addItem(temp);
					System.out.println("The Store Value is: "+temp);
				}
			}
			catch(Exception e)
			{
				System.out.println("The Reading Exception: "+e.toString());
			}
		}
		
		/*This method is called from within the constructor to initialize the form
		  WARNING: DO NOT modify this code. The content of this method is always 
		  Regenerated by the Form editor
		*/
		//GEN-BEGIN:initComponents
		private void initComponents() {
			
			jLabel2 = new javax.swing.JLabel();
			jPanel1 = new javax.swing.JPanel();
			jLabel4 = new javax.swing.JLabel();
			jLabel5 = new javax.swing.JLabel();
			jTextField1 = new javax.swing.JTextField();
			jButton1 = new javax.swing.JButton();
			jButton2 = new javax.swing.JButton();
			jButton3 = new javax.swing.JButton();
			jComboBox1 = new javax.swing.JComboBox();
			jLabel1 = new javax.swing.JLabel();
			jLabel3 = new javax.swing.JLabel();
			
			jLabel2.setText("JLabel2");
			setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
			setResizeable(false);
			
			jPanel1.setBackground(Color.blue);
			jPanel1.setLayout(null);
			
			jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); //NOI18N
			jLabel4.setForeground(new java.awt.Color(212, 166, 96));
			jLabel4.setText("Choose the file");
			jPanel1.add(jLabel4);
			jLabel4.setBounds(70, 150, 190, 40);
			
			jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); //NOI18N
			jLabel5.setForeground(new java.awt.Color(212, 166, 96));
			jLabel5.setText("IP Adress");
			jPanel1.add(jLabel5);
			jLabel5.setBounds(80, 220, 130, 40);
			
			jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); //NOI18N
			jPanel1.add(jTextField1);
			jTextField1.setBounds(280, 156, 130, 34);
			
			jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24));
			jButton1.setText("Browse");
			jButton1.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					jButton1ActionPerformed(evt);
				}
			});
			jPanel1.add(jButton1);
			jButton1.setBounds(50, 330, 120, 40);
			
			jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24));
			jButton2.setText("Send");
			jButton2.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					jButton2ActionPerformed(evt);
				}
			});
			jPanel1.add(jButton2);
			jButton2.setBounds(210, 330, 120, 40);
			
			jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24));
			jButton3.setText("Cancel");
			jButton3.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					jButton3ActionPerformed(evt);
				}
			});
			jPanel1.add(jButton3);
			jButton3.setBounds(370, 330, 120, 37);
			
			jComboBox1.addItemListener(new java.awt.event.ItemListener() {
				public void itemStateChanged(java.awt.event.ItemEvent evt) {
					jComboBox1itemStateChanged(evt);
				}
			});
			jPanel1.add(jComboBox1);
			jComboBox1.setBounds(80, 220, 130, 40);
			
			jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); //NOI18N
			jLabel1.setForeground(new java.awt.Color(212, 166, 96));
			jLabel1.setText("A New Reliable Broadcassting For");
			jPanel1.add(jLabel1);
			jLabel1.setBounds(80, 10, 370, 40);
			
			jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); //NOI18N
			jLabel3.setForeground(new java.awt.Color(212, 166, 96));
			jLabel3.setText(" Mobile Adhoc Networks");
			jPanel1.add(jLabel3);
			jLabel5.setBounds(120, 60, 290, 30);
			
			/*
			javax.swing.GroupLayout = newjavax.swing.GroupLayout(getContentPane());
			getContentPane().setLayout(layout);
			layout.setHorizontalGroup(
					layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).
					addComponent(jPanel1,javax.swing.GroupLayout.Alignment.TRAILING,
					javax.swing.GroupLayout.DEFAULT_SIZE,537,Short.MAX_VALUE));
			layout.setVerticalGroup(	
					layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).
					addComponent(jPanel1,javax.swing.GroupLayout.DEFAULT_SIZE,415,Short.MAX_VALUE)); 
			*/
			
			getContentPane().add(jPanel1);
		}//</editor-fold>//GEN-END:initComponents
		
		private void jComboBox1itemStateChanged(java.awt.event.ItemEvent evt) {
			//GEN-FIRST:event_jComboBox1itemStateChanged
			//TO-DO: Add handling code here
			jcombovalue = jComboBox1.getSelectedItem().toString();
			/*Vector vec = new Vector();
			 * for(int i=0; i<jcombovalue.length();i++)
			 * {
			 * 		vec.addElement(jcomboValue);
			 * 		System.out.println("The selected value is: "+jcombovalue);
			 * }
			*/j++;
		}//GEN-LAST:event_jComboBox1itemStateChanged
		
		private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
			//GEN-FIRST:event_jButton3ActionPerformed
			//TO-DO: Add handling code here
			System.exit(0);
		}//GEN-LAST:event_jButton3ActionPerformed
		
		private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
			//GEN-FIRST:event_jButton2ActionPerformed
			//TO-DO: Add handling code here
			if(evt.getSource()==jButton2) {
					try
					{
						new Thread(this).start();
					}
					catch(Exception e) 
					{
						System.out.println("ffff" +e);
					}
			}
			
			public void run() {
				for(i=0; i<vec.size(); i++) {
					try
					{
						System.out.println("path" +path);
						int j=0;
						ip = vec.get(i).toString();
						System.out.println("The IP value is: " +ip);
						Socket soc = new Socket(ip,1234);
						PrintWriter pw = new PrintWriter(soc.getOutputStream(), true);
						pw.println();
						;
						Socket soc2 = new Socket(ip.toString(),4321);
						PrintWriter pw1 = new PrintWriter(soc2.getOutputStream(), true);
						System.out.println("Before forwarding " +filecontent);
						pw.println(filecontent);
						soc.close();
						soc2.close();
						pw1.close();
					}
					catch(Exception e) 
					{
						//JOptionPane.showMessageDialog(null,"The given IP Address are not active"
						//+vec.get(i).toString());
						System.out.println("The Sending Exception: " +e.toString());
					}
					System.out.println("The forward content is: " +filecontent);
					//JOptionPane.showMessageDialog(null,"The given IP Address are active: " +ip);
				}
			}
		}//GEN-LAST:event_jButton2ActionPerformed
			
		private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
			//GEN-FIRST:event_jButton1ActionPerformed
			//TO-DO: Add handling code here
			if(evt.getSource()==jButton1) {
					try
					{
						fc = new JFileChooser();
						int option = fc.showOpenDialog(jLabel2);
						if(option == fc.APPROVE_OPTION)
						{
							path = fc.getSelectedFile().getAbsolutePath();
							System.out.println("The path details are: " =path);
							file = fc.getSelectedFile().getName();
							System.out.println("The file list is: " +file);
							jTextField1.setText(path);
							filename = jTextField1.getText();
							System.out.println("The file content is" +filename);
							FileInputStream fis = new FileInputStream(path);
							//fis.getBytes();
							//byte str[] = new byte[60000];
							fis.read(content,0,content.length);
							filecontent = new String(content);
							System.out.println("The file Content Is: " +filecontent.trim());
						}
					}
					catch(Exception e)
					{
						System.out.println("The Exception in browsing is: " +e.toString());
					}
			}
		}//GEN-LAST:event_jButton1ActionPerformed
			
		Vector loadLanUser() {
			Vector vect = = null;
			try 
			{
				Process p = Runtime.getRuntime().exec("net view");
				System.out.println("p= " +p);
				BufferedInputStream bis = new BufferedInputStream(p.getInputStream());
				StringBuffer sb=new StringBuffer();
				int c=0;
				while((c=bis.read()) != -1) {
					sb.append(((char)c));
					//System.out.println("sb= " +sb);
				}
				String outputText = sb.toString();
				System.out.println("OutputText= " +outputText);
				java.util.StringTokenizer tokenizer = new java.util.StringTokenizer(outputText, "\n");
				String lastMacAddress;
				vect=new Vector();
				while(tokenizer.hasMoreTokens()) {
					String line = tokenizer.nextToken().trim();
					int len = line.length();
					if(len>2) {
						str = line.substring(0, 2);
						if(str.compareTo("\\") == 1) {
							count++;
							line = line.substring(2, len);
							//String hostaddr1 = java.net.InetAddress.getLocalHost().getHostName();
							/* if(line.equalsIgnoreCase(hostaddr1))
								{
								else
								{
							*/
							vect,addElement(line);
						//}
					}
				}
			}
			}
			catch(Exception e) 
			{
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			return vect;
		}
		
		/**
		 * @param args the command line arguments
		 */
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		new sourceModule().setVisible(true);
	}
	
	//Variables declaration - do not modify // GEN-BEGIN: Variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	
	private javax.swing.JComboBox jComboBox1;
	
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	
	private javax.swing.JPanel jPanel1;
	
	private javax.swing.JTextField jTextField1;
	// End of Variables declaration //GEN-END: Variables
}
